### PR TITLE
Split SQS from fs2-aws module to fs2-aws-sqs and 

### PR DESCRIPTION
**Pull request by jatcwang**
Separate SQS from fs2-aws module to reduce dependency footprint.

- Moved SQS code to `fs2-aws-sqs` and `fs2-aws-sqs-testkit`
- SQS Testkit classes now resides in `fs2.aws.sqs.testkit`
- Fix SqsSpec that isn't actually being run

### CODE REVIEW

**Comment by barryoneill** [comment]
Thank you!

**Comment by barryoneill** [comment]
Please update docs for the new dependency that folks will have to add.

**Comment by jatcwang** [comment]
@barryoneill is there a changelog file I can write to?

**Comment by barryoneill** [comment]
There isn't (yet!).  Actually, don't worry about it.  We need to fix up our README anyway before the next major version

**Pull request merged**
