### PR TITLE
Upgrade fs2 to 3.2.0 that depends on cats-effect 3 (instead of 2). 

### PR DESCRIPTION
**Pull request by kovacshuni**
This way evicting cats-effect 2 from this project for other projects that use this library, using CE 3 and might conflict with 2

### CODE REVIEW

**Comment by kovacshuni** [comment]
Build got cancelled. Why?

**Comment by semenodm** [comment]
we have some problems with the latest versions of fs2. I need to rewrite kinesis module tests

**Comment by semenodm** [comment]
just fixed the tests, the fs2 dependency has been updated in other branch

**Comment by semenodm** [comment]
gg

**Comment by kovacshuni** [comment]
Thanks for upgrading anyways.

**Pull request closed without merging**
